// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trimly.Infrastructure.Data;

#nullable disable

namespace Trimly.Infrastructure.Migrations
{
    [DbContext(typeof(TrimlyDbContext))]
    [Migration("20260505094207_RedisenioDominio")]
    partial class RedisenioDominio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trimly.Domain.Entities.Barberia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Barberias");
                });

            modelBuilder.Entity("Trimly.Domain.Entities.BarberiasBarberos", b =>
                {
                    b.Property<int>("BarberoId")
                        .HasColumnType("integer");

                    b.Property<int>("BarberiaId")
                        .HasColumnType("integer");

                    b.HasKey("BarberoId", "BarberiaId");

                    b.HasIndex("BarberiaId");

                    b.ToTable("BarberiasBarberos");
                });

            modelBuilder.Entity("Trimly.Domain.Entities.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BarberoId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BarberoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("Trimly.Domain.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Pefiles");
                });

            modelBuilder.Entity("Trimly.Domain.Entities.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Trimly.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Trimly.Domain.Entities.Barberia", b =>
                {
                    b.HasOne("Trimly.Domain.Entities.Usuario", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Trimly.Domain.Entities.BarberiasBarberos", b =>
                {
                    b.HasOne("Trimly.Domain.Entities.Barberia", "Barberia")
                        .WithMany("BarberiasBarberos")
                        .HasForeignKey("BarberiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trimly.Domain.Entities.Usuario", "Barbero")
                        .WithMany("BarberiasBarberos")
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barberia");

                    b.Navigation("Barbero");
                });

            modelBuilder.Entity("Trimly.Domain.Entities.Cita", b =>
                {
                    b.HasOne("Trimly.Domain.Entities.Usuario", "Barbero")
                        .WithMany("CitasComoBarbero")
                        .HasForeignKey("BarberoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trimly.Domain.Entities.Usuario", "Cliente")
                        .WithMany("CitasComoCliente")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trimly.Domain.Entities.Servicio", "Servicio")
                        .WithMany("Citas")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbero");

                    b.Navigation("Cliente");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Trimly.Domain.Entities.Perfil", b =>
                {
                    b.HasOne("Trimly.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Perfil")
                        .HasForeignKey("Trimly.Domain.Entities.Perfil", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Trimly.Domain.Entities.Barberia", b =>
                {
                    b.Navigation("BarberiasBarberos");
                });

            modelBuilder.Entity("Trimly.Domain.Entities.Servicio", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("Trimly.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("BarberiasBarberos");

                    b.Navigation("CitasComoBarbero");

                    b.Navigation("CitasComoCliente");

                    b.Navigation("Perfil");
                });
#pragma warning restore 612, 618
        }
    }
}
